import json
import os

from slack_sdk import WebClient
from slack_sdk.errors import SlackApiError

from src.api.standup import FIELDS, DEFAULT_STALE_DAYS, build_standup_payload, _ticket_label
from src.clients import oauth_store
from src.clients.jira import get_myself, resolve_auth, resolve_base_url, search_issues
from src.clients.slack_dm import mention_tag, open_dm, slack_text_with_mentions, slack_user_id


def _issue_lines(title: str, items: list[dict]) -> list[str]:
    lines = [title]
    if not items:
        lines.append("• None")
        return lines
    for item in items:
        status = item.get("status")
        label = _ticket_label(item)
        if status:
            label = f"{label} ({status})"
        lines.append(f"• {label}")
    return lines


def _prep_text(project_key: str, person: dict, payload: dict, mention: str | None = None) -> str:
    name = mention or person.get("displayName") or "there"
    ai = payload.get("ai") or {}
    lines = [
        f"DSU prep for {name}",
        f"Project {project_key}",
        "Answer these in standup. Use this to prepare.",
        "",
        "Your work",
    ]
    lines.extend(_issue_lines("Blocked", person.get("blocked") or []))
    lines.extend(_issue_lines("In progress", person.get("in_progress") or []))
    lines.extend(_issue_lines("Done since yesterday", person.get("done_yesterday") or []))
    questions = person.get("questions") or ai.get("questions") or []
    if questions:
        lines.extend(["", "Questions to answer in DSU"])
        lines.extend(f"• {item}" for item in questions)
    if ai.get("status") == "ok" and ai.get("summary"):
        lines.extend(["", "Team brief", ai["summary"]])
        asks = ai.get("asks") or []
        if asks:
            lines.append("")
            lines.append("Suggested asks for others")
            lines.extend(f"• {ask}" for ask in asks)
    lines.extend(["", "Generated by WorkBridge"])
    return "\n".join(lines)


def _parse_body(event) -> dict:
    raw = event.get("body") if isinstance(event, dict) else None
    if not raw:
        return {}
    if event.get("isBase64Encoded"):
        import base64

        raw = base64.b64decode(raw).decode()
    if isinstance(raw, dict):
        return raw
    try:
        return json.loads(raw)
    except Exception:
        return {}


def _person_from_me(me: dict, myself: dict | None, payload: dict) -> dict:
    ai = payload.get("ai") or {}
    return {
        "accountId": me.get("accountId") or (myself or {}).get("accountId"),
        "displayName": me.get("displayName") or (myself or {}).get("displayName") or "you",
        "email": (myself or {}).get("emailAddress"),
        "blocked": me.get("blocked") or [],
        "in_progress": me.get("in_progress") or [],
        "done_yesterday": me.get("done_yesterday") or [],
        "questions": ai.get("questions")
        or [
            "What did you finish yesterday?",
            "What will you work on today?",
            "What is blocked, and who can help?",
        ],
    }


def _extra_user_ids() -> list[str]:
    raw = os.environ.get("SLACK_PREP_USER_IDS") or ""
    return [item.strip() for item in raw.split(",") if item.strip()]


def handler(event, context):
    try:
        workspace = oauth_store.get_workspace() or {}
        body = _parse_body(event)
        project_key = (
            body.get("projectKey")
            or workspace.get("standup_project_key")
            or os.environ.get("STANDUP_PROJECT_KEY")
            or ""
        ).upper()
        token = workspace.get("slack_bot_token") or os.environ.get("SLACK_BOT_TOKEN")
        if not project_key:
            raise RuntimeError("Select a Jira project in WorkBridge so 09:50 prep DMs know which board to use")
        if not token:
            raise RuntimeError("Connect Slack first")

        auth = resolve_auth(event if isinstance(event, dict) else None)
        site = resolve_base_url(auth)
        myself = None
        try:
            myself = get_myself(auth=auth)
        except Exception:
            myself = None

        data = search_issues(
            jql=f"project = {project_key} ORDER BY updated DESC",
            fields=FIELDS,
            max_results=50,
            auth=auth,
        )
        payload = build_standup_payload(
            issues=data.get("issues") or [],
            site=site,
            project_key=project_key,
            jql=f"project = {project_key} ORDER BY updated DESC",
            myself=myself,
            stale_days=DEFAULT_STALE_DAYS,
        )

        client = WebClient(token=token)
        cache: dict = {}
        sent = []
        skipped = []
        to_me = bool(body.get("toMe"))
        target_account = (body.get("accountId") or "").strip()
        target_slack = (body.get("slackUserId") or "").strip()
        people = payload.get("assignees") or []
        me = payload.get("me") or {}
        if to_me and not target_account:
            target_account = (me.get("accountId") or "").strip()
        if to_me:
            people = [person for person in people if person.get("accountId") == target_account]
            if not people:
                people = [_person_from_me(me, myself, payload)]
            elif myself and myself.get("emailAddress") and not people[0].get("email"):
                people[0]["email"] = myself.get("emailAddress")
        elif target_account:
            people = [person for person in people if person.get("accountId") == target_account]
            if not people:
                raise RuntimeError("No work found for that user on this project")

        for person in people:
            user_id = target_slack or slack_user_id(
                client,
                email=person.get("email"),
                display_name=person.get("displayName"),
                cache=cache,
            )
            if to_me and not user_id:
                user_id = workspace.get("slack_authed_user_id")
            if not user_id:
                skipped.append(person.get("displayName") or person.get("accountId"))
                continue
            mention = mention_tag(user_id, person.get("displayName"))
            text = slack_text_with_mentions(
                client,
                _prep_text(project_key, person, payload, mention),
                payload,
                myself=myself,
                cache=cache,
            )
            channel = open_dm(client, user_id)
            client.chat_postMessage(channel=channel, text=text)
            sent.append(user_id)
            if target_account or target_slack or to_me:
                break

        if to_me and not sent:
            fallback = target_slack or workspace.get("slack_authed_user_id")
            if fallback:
                person = people[0] if people else _person_from_me(me, myself, payload)
                mention = mention_tag(fallback, person.get("displayName"))
                text = slack_text_with_mentions(
                    client,
                    _prep_text(project_key, person, payload, mention),
                    payload,
                    myself=myself,
                    cache=cache,
                )
                channel = open_dm(client, fallback)
                client.chat_postMessage(channel=channel, text=text)
                sent.append(fallback)

        if target_slack and not sent:
            extra_text = slack_text_with_mentions(
                client,
                payload.get("text") or "DSU prep is ready in WorkBridge.",
                payload,
                myself=myself,
                cache=cache,
            )
            channel = open_dm(client, target_slack)
            client.chat_postMessage(
                channel=channel,
                text=f"{mention_tag(target_slack)}\nDSU prep\nProject {project_key}\n\n{extra_text}",
            )
            sent.append(target_slack)

        if not target_account and not target_slack and not to_me:
            extra_text = slack_text_with_mentions(
                client,
                payload.get("text") or "DSU prep is ready in WorkBridge.",
                payload,
                myself=myself,
                cache=cache,
            )
            for user_id in _extra_user_ids():
                if user_id in sent:
                    continue
                channel = open_dm(client, user_id)
                client.chat_postMessage(
                    channel=channel,
                    text=f"{mention_tag(user_id)}\nDSU prep\nProject {project_key}\n\n{extra_text}",
                )
                sent.append(user_id)

        return {
            "statusCode": 200,
            "headers": {"Content-Type": "application/json"},
            "body": json.dumps({"data": {"sent": sent, "skipped": skipped, "projectKey": project_key}}),
        }
    except SlackApiError as exc:
        return {
            "statusCode": 502,
            "headers": {"Content-Type": "application/json"},
            "body": json.dumps(
                {"error": f"Slack API error: {exc.response.get('error', str(exc))}"}
            ),
        }
    except Exception as exc:
        return {
            "statusCode": 500,
            "headers": {"Content-Type": "application/json"},
            "body": json.dumps({"error": str(exc)}),
        }
