import json
from datetime import datetime, timezone

from src.api._jira_auth import credentials_from_event
from src.clients.jira import resolve_base_url, search_issues

FIELDS = ["summary", "status", "assignee", "priority", "issuetype", "labels"]


def _bucket(status_name: str, labels: list) -> str:
    status = (status_name or "").lower()
    label_set = {str(label).lower() for label in (labels or [])}
    if "blocked" in status or "blocked" in label_set:
        return "blocked"
    if status in {"in progress", "in review", "doing"}:
        return "in_progress"
    if status in {"done", "closed", "resolved", "complete"}:
        return "done"
    return "todo"


def _format_line(item: dict) -> str:
    assignee = item.get("assignee") or "Unassigned"
    status = item.get("status") or "Unknown"
    return f"• [{item['key']}] {item['summary']} — {assignee} ({status})"


def _build_text(project_key: str, groups: dict) -> str:
    today = datetime.now(timezone.utc).strftime("%d %b %Y")
    total = sum(len(items) for items in groups.values())
    counts = {key: len(value) for key, value in groups.items()}

    lines = [
        f"Daily Standup — Project {project_key}",
        f"Date: {today} (UTC)",
        f"Summary: {total} issues | "
        f"Blocked {counts['blocked']} · In Progress {counts['in_progress']} · "
        f"To Do {counts['todo']} · Done {counts['done']}",
        "",
    ]

    sections = [
        ("Blocked", "blocked"),
        ("In Progress / In Review", "in_progress"),
        ("To Do", "todo"),
        ("Done", "done"),
    ]

    for title, key in sections:
        items = groups[key]
        lines.append(f"{title} ({len(items)})")
        if items:
            lines.extend(_format_line(item) for item in items)
        else:
            lines.append("• No items")
        lines.append("")

    lines.append("Generated by WorkBridge")
    return "\n".join(lines).rstrip() + "\n"


def handler(event, context):
    try:
        path_params = event.get("pathParameters") or {}
        query = event.get("queryStringParameters") or {}
        project_key = (path_params.get("projectKey") or "KAN").upper()
        jql = query.get("jql") or f"project = {project_key} ORDER BY cf[10019] ASC"
        max_results = int(query.get("maxResults") or 50)
        creds = credentials_from_event(event)
        site = resolve_base_url(creds["base_url"])

        data = search_issues(
            jql=jql,
            fields=FIELDS,
            max_results=max_results,
            email=creds["email"],
            token=creds["token"],
            base_url=creds["base_url"],
        )

        groups = {"todo": [], "in_progress": [], "done": [], "blocked": []}
        for issue in data.get("issues") or []:
            fields = issue.get("fields") or {}
            status = (fields.get("status") or {}).get("name")
            item = {
                "key": issue.get("key"),
                "summary": fields.get("summary"),
                "status": status,
                "assignee": (fields.get("assignee") or {}).get("displayName"),
                "url": f"{site}/browse/{issue.get('key')}",
            }
            groups[_bucket(status, fields.get("labels") or [])].append(item)

        payload = {
            "projectKey": project_key,
            "jql": jql,
            "counts": {key: len(value) for key, value in groups.items()},
            **groups,
            "text": _build_text(project_key, groups),
        }

        return {
            "statusCode": 200,
            "headers": {"Content-Type": "application/json"},
            "body": json.dumps({"data": payload}),
        }
    except Exception as exc:
        return {
            "statusCode": 500,
            "headers": {"Content-Type": "application/json"},
            "body": json.dumps({"error": str(exc)}),
        }
